### ISSUE TITLE
Doesn't publish it's own feed?

### ISSUE THREAD

**Issue by nateberkopec** [jrochkind/rubyland#1]
Am I correct that there's no Rubyland RSS feed?

**Comment by jrochkind** [comment]
You are correct there is not yet. I definitely plan one. 

I hadn't really 'released' this yet, although it is there in public. Just curious, how did you find it? You find it useful?  Plan to do a public announcement 'release' soon, although it prob still won't have it's own feed yet. 

What's your use for an aggregated feed? There are several things I want to add, I can bump that up in priority.

**Comment by nateberkopec** [comment]
👍  @schneems told me about it. 

I love it! I want to be able to just add it to The Old Reader, but I might also enjoy a weekly digest email.

**Comment by jrochkind** [comment]
Awesome. @schneems is in fact the only person I had told about it so far other than my coworkers, ha. But I plan to try to announce it widely soonish. 

I def plan to add an aggregated feed.  Also an OPML representation of all the aggregated feeds, if you prefer to merge it that way.  It's only been on the internet like five days at the moment. :)

**Comment by jrochkind** [comment]
I did not have plans to add digest emails, but it's an interesting idea. Prob won't happen unless I get a 'sponsor' to pay for hosting/deployment costs, not sure I can send bulk emails for free, right now it's running on heroku free dyno with no expenses but the domain.

**Comment by jrochkind** [comment]
Any other feedback welcome, since you're essentially the only beta tester at the moment. Is the typography readable? I spent a lot of time on it because it's not my typical skillset, and I _think_ it looks pretty good, but I've stared at it so long I can't be sure anymore.

**Comment by nateberkopec** [comment]
Yeah it's good. I prefer larger font sizes but that's down to taste. TBH I think what's there is launchable, not sure what you think is missing. You just need some way to "capture" subscribers to keep people coming back - RSS and digest emails are really the only good ways to do that. Probably a Twitter feed too.

**Comment by jrochkind** [comment]
Cool, thanks. It's all in terms of `rem`, so you can just bump font size on your browser, and it'll all look fine. 

It's not really a profit-making venture, so I'm not too worried about capturing subscribers, they can come back if it's useful or not if it's not, all fine with me. The aggregated RSS feed would direct users to the original posts, not to the rubyland site, so wouldn't really capture them for rubyland anyway. Which is fine. 

I had considered a twitter feed of everything, thanks for reminding me. 

Cool, I think it's launchable too, at this point I was just working out some deployment issues, like DNS, that I worked on yesterday. And making sure the feed downloading stuff was working right by letting it go a few days in live production. 

Thanks, appreciate it!

**Comment by nateberkopec** [comment]
> they can come back if it's useful or not if it's not, all fine with me. 

I don't mean as a profitmaking thing. I mean Rubyland would be _more useful to me_ if it reminded me to come back and check every once in a while.

**Comment by jrochkind** [comment]
Aha, I gotcha!

**Comment by jrochkind** [comment]
It does now! Also bumped up the font size.

**Comment by jrochkind** [comment]
@nateberkopec there's a twitter feed now too. Still working out some of the kinks, but https://twitter.com/rubylandnews
