### ISSUE TITLE
RSS feed needs authorship/attribution

### ISSUE THREAD

**Issue by nateberkopec** [jrochkind/rubyland#10]
<img width="1021" alt="screen shot 2016-12-31 at 11 26 20 am" src="https://cloud.githubusercontent.com/assets/845662/21578588/0f281f14-cf4c-11e6-83d2-45c3e3cf90ce.png">

IMO, I'd prefer something like "originally appeared at <domain>", where domain is a link to the post.

**Comment by jrochkind** [comment]
Good point. It does include attribution in the RSS XML, but in a `<source>` tag that most readers don't show I guess. 

Are you thinking at the bottom of the text, just in the text?

**Comment by nateberkopec** [comment]
For usability's sake, I'd prefer it right at the top.

**Comment by jrochkind** [comment]
You'd suggest the "originally appeared at" is a link to the specific post -- same thing the RSS item as a whole links to, which you probably get clicking on the title?  Would also be possible to make the link to the original source home page, we have that info. 

Alternately, as another UX approach, I could just change the title of the entry in the feed to include the source: `Stories by dhh on medium: Writing Software Is Hard`.

**Comment by nateberkopec** [comment]
I probably wouldn't change the title, as most blog titles are long enough already, so adding a source there will just make titles get truncated/wrap in certain readers.

Your call on what's best. My suggestion is "Originally appeared on <blogname + link>".

**Comment by jrochkind** [comment]
oops, not yet, heh.
