### ISSUE TITLE
Don't publish Medium comments? (@dhh medium feed removed cause no way to filter out comments)

### ISSUE THREAD

**Issue by nateberkopec** [jrochkind/rubyland#13]
On Medium, author comment replies end up in the RSS feed. This ends up clogging my RSS feed, with one-word replies like "Yes" :|

**Comment by jrochkind** [comment]
Yeah, I noticed dhh just spammed us. 

I've been trying to figure out a way to filter comments out of medium feeds, but there's no way to, or no way I can figure out. (shakes fist at medium).  I guess I'll remove dhh's feed, and other medium feeds. 

I could add a feed of _all_ posts tagged 'ruby' on medium, which looks like it just includes actual posts and not comments, but it would add like 2-4 posts a day to the feed, from all over medium, of varying quality. Any opinions on that?

**Comment by nateberkopec** [comment]
> I could add a feed of all posts tagged 'ruby' on medium, which looks like it just includes actual posts and not comments, but it would add like 2-4 posts a day to the feed, from all over medium, of varying quality. Any opinions on that?

Meh. I like the curation so far, avoids any total garbage spam, etc.

**Comment by nateberkopec** [comment]
Could you fix this by adding the Signal vs Noise feed, rather than the DHH feed? Then I guess you add all the non-DHH, non-Ruby related posts as well.

**Comment by jrochkind** [comment]
Yeah, I thought of that, there's a lot non-ruby related in Signal v. Noise, but maybe I'll try that. 

Really, the problem is Medium and their poor support for feeds. :(  But I'll go ahead and remove dhh.
