### ISSUE TITLE
New Feed - Monthly What's Up? Ruby Conferences & Camps from Around the World @ Planet Ruby

### ISSUE THREAD

**Issue by geraldb** [jrochkind/rubyland#15]
Hello,
   as promised here's the suggested feed for ruby conferences and camps. The plan for now is to publish a new item (summary) every month (that is, monthly updates).

   Get the feed @ https://planetruby.github.io/calendar/feed.xml   and see the first post @ https://planetruby.github.io/calendar/2018/1

   Would be great to see it added on Rubyland. if you have any questions or comments, let me know. Keep it up. Cheers.

**Comment by jrochkind** [comment]
Sounds good! is it possible to put a more informative 'title' in the feed?
Rubyland uses the title from the feed. I think it probably ignores the
<subtitle>, but can't remember. Here's what it looks like now, title just
"calendar".  And I'm not sure if ruby advent calendar is meant to be in the
<subtitle>, but I think rubyland ignores it anyway if I recall correctly.

<title type="html">calendar</title>
<subtitle>
Calendar | Ruby Conferences & Camps in 2018 - What's Upcoming? ++ Ruby
Advent Calendar 2017 - 25 Days of Ruby Gems / Libraries, December 1 -
December 25 (incl. Ruby 2.5 - What's News?)
</subtitle>

**Comment by geraldb** [comment]
Thanks for trying. Good point. Using the jekyll feed plugin. Changed the site.title to:

> Ruby Conferences ‘n’ Camps in 2018 - What’s Upcoming?

Please try again (reload) and you should see the new title. Greetings from Vienna. Cheers.

**Comment by jrochkind** [comment]
Done!

**Comment by geraldb** [comment]
Wow. Fantastic. What a joy your Rubyland planet site. Keep it up. Also added to the Awesome News page @ Planet Ruby -> https://github.com/planetruby/awesome-news   Cheers.
