### ISSUE TITLE
Use Cloudflare on rubyland.news

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [jrochkind/rubyland#2]
Concerning the lack of secure access and low-budget resource problem, as spelled out in [post](https://bibwild.wordpress.com/2016/11/16/rubyland-a-new-ruby-news-and-blog-feed-aggregator/), I would suggest you to look at a [free tier of Cloudflare](https://www.cloudflare.com/plans/).

It will provide you with solid DNS, free SSL certificate and "site-offline" cache plus general speedup/CDN for folks around the world. Not to mention the added security of hiding and reducing hit rate to Heroku origin.

**Comment by jrochkind** [comment]
Thanks for the suggestion. I did look at Cloudflare, but decided the added security it provides in this particular situation is pretty minimal/illusory (although it does make browsers think things are secure, which may be important if browsers start warning more heavily), and the CDN was probably not neccesary at this point. But I'll def keep it in mind should issues arise that seem like cloudflare could help with. 

Are you having speed/performance problems with rubyland.news at present, from your location?

**Comment by aleksandrs-ledovskis** [comment]
@jrochkind No, site loads fast. This was just a suggestion/another option on the table. ☮️
