### ISSUE TITLE
New Feed Suggestion - 25 Days of Ruby Gems - Ruby Advent Calendar 2020, December 1st - December 25th

### ISSUE THREAD

**Issue by geraldb** [jrochkind/rubyland#35]
Hello,  first thanks for keeping the fantastic (public) news reader up and running.

Sorry if this is the wrong channel (I try to send you an email too - sorry for the duplicate) -   Better later than never - for the Ruby Advent Calendar ongoing since December 1st I finally added the missing /feed.xml  (in atom). 
It would be great to see the feed getting added on Rubyland.  If you have any questions or comments, let me know. Keep it up. Cheers.

PS: Here the links / urls:
- feed_url: <https://planetruby.github.io/gems/feed.xml>
- site_url: <https://planetruby.github.io/gems/>

**Comment by jrochkind** [comment]
Sure, I'll add it, thanks!

**Comment by geraldb** [comment]
Thanks for adding the feed. Cheers. Prost.
